#!/usr/bin/env python3
"""Metadata-only coverage census for the 2026-09-21 19:00–22:00 JST Tohoku event.

Only inspect F4-9A source-archive manifests under cohort/sources.
NEVER open F4-9C verification, forecasts, post-event observations,
cohort status, scored data, radar NPZ bytes, or remote resources.
No scientific result is generated by this metadata inventory.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

TARGET_END = datetime(2026, 9, 21, 13, 0, tzinfo=timezone.utc)
TARGET_START = TARGET_END - timedelta(hours=3)
STEP = timedelta(minutes=5)
EXPECTED = tuple(TARGET_START + STEP * i for i in range(37))


def utc(value: str) -> datetime:
    parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError("naive source time rejected")
    return parsed.astimezone(timezone.utc)


def stamp(value: datetime) -> str:
    return value.isoformat(timespec="seconds").replace("+00:00", "Z")


def fixed_key(value: dict[str, Any]) -> tuple[int, int, int, int]:
    return (
        int(value["zoom"]),
        int(value["origin_tile_x"]),
        int(value["origin_tile_y"]),
        int(value["tile_count"]),
    )


def inventory(cohort_root: Path, reference_case: Path) -> dict[str, Any]:
    case = json.loads(reference_case.read_text(encoding="utf-8"))
    if (
        case.get("product") != "F4_9C_PROSPECTIVE_CASE"
        or utc(case["source_slot_utc"]) != TARGET_END
        or case.get("risk_engine_allowed") is not False
    ):
        raise ValueError("reference frozen case contract mismatch")
    reference_key = fixed_key(case["fixed_mosaic"])
    roots = cohort_root / "sources"
    if not roots.is_dir():
        raise FileNotFoundError(f"F4-9A source archive directory missing: {roots}")

    domains: dict[tuple[int, int, int, int], dict[str, Any]] = defaultdict(
        lambda: {
            "source_archives": 0,
            "source_slots": set(),
            "times": Counter(),
            "source_files_present": 0,
            "source_files_missing": 0,
            "invalid_or_out_of_window": 0,
        }
    )
    skipped_after_event = 0
    malformed = []
    for manifest_path in sorted(roots.glob("*/manifest.json")):
        try:
            doc = json.loads(manifest_path.read_text(encoding="utf-8"))
            if doc.get("product") != "F4_DECODED_FIELD_RESEARCH_ARCHIVE":
                malformed.append(f"{manifest_path.name}:unexpected-product")
                continue
            timestamps = [utc(value) for value in doc["frame_valid_times"]]
            if len(timestamps) != 4 or any(
                timestamps[i + 1] - timestamps[i] != STEP for i in range(3)
            ):
                malformed.append(f"{manifest_path.parent.name}:invalid-source-cadence")
                continue

            # Skip source manifests containing *any* observation later than
            # this case's last pre-capture observation. Do not inspect targets.
            if max(timestamps) > TARGET_END:
                skipped_after_event += 1
                continue

            key = fixed_key(doc["fixed_mosaic"])
            domain = domains[key]
            domain["source_archives"] += 1
            if TARGET_START <= max(timestamps):
                domain["source_slots"].add(stamp(max(timestamps)))
                archive_file = doc.get("storage", {}).get("file")
                if archive_file == "decoded_field.npz":
                    available = (manifest_path.parent / archive_file).is_file()
                    domain["source_files_present" if available else "source_files_missing"] += 1
                else:
                    domain["source_files_missing"] += 1
                for ts in timestamps:
                    if TARGET_START <= ts <= TARGET_END:
                        domain["times"][ts] += 1
            else:
                domain["invalid_or_out_of_window"] += 1
        except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            malformed.append(f"{manifest_path.parent.name}:{type(exc).__name__}")

    summaries = []
    for key, domain in sorted(domains.items()):
        found = domain["times"]
        missing = [stamp(ts) for ts in EXPECTED if ts not in found]
        duplicates = [stamp(ts) for ts in EXPECTED if found[ts] > 1]
        summaries.append(
            {
                "fixed_mosaic": dict(
                    zip(("zoom", "origin_tile_x", "origin_tile_y", "tile_count"), key)
                ),
                "is_event_case_mosaic": key == reference_key,
                "archives_in_window": len(domain["source_slots"]),
                "source_slots_utc": sorted(domain["source_slots"]),
                "unique_five_minute_frames_of_37": len(EXPECTED) - len(missing),
                "missing_frame_count": len(missing),
                "missing_frames_utc": missing,
                "duplicate_frame_count": len(duplicates),
                "source_npz_present_count": domain["source_files_present"],
                "source_npz_missing_count": domain["source_files_missing"],
                "metadata_full_window": not missing,
                "raw_radar_archive_bytes_read": False,
            }
        )
    event = next((x for x in summaries if x["is_event_case_mosaic"]), None)
    return {
        "audit": "F4_20260921_PRE_SOURCE_3H_AVAILABILITY_CENSUS",
        "event_start_utc": stamp(TARGET_START),
        "event_end_utc": stamp(TARGET_END),
        "event_mosaic": case["fixed_mosaic"],
        "required_five_minute_frame_timestamps": 37,
        "matching_event_mosaic_coverage": event or {
            "metadata_full_window": False,
            "unique_five_minute_frames_of_37": 0,
        },
        "source_domain_inventory": summaries,
        "manifests_skipped_because_source_after_event": skipped_after_event,
        "malformed_manifest_count": len(malformed),
        "malformed_manifest_samples": malformed[:10],
        "read_f4_9c_verifications": False,
        "read_future_observations": False,
        "read_radar_npz_bytes": False,
        "downloaded_files": 0,
        "scientific_note": (
            "Even full 5-minute public categorical radar coverage would be a "
            "5-minute-cadence continuity / intensity-class proxy; it cannot "
            "reproduce exact JMA 5-km 3-hour analyzed-rainfall occurrence criteria. "
            "Unknown pixels must not be zero-filled. Grid/mosaic switches must not "
            "be stitched as a single unchanged analysis footprint."
        ),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cohort-root", required=True, type=Path)
    ap.add_argument("--reference-case", required=True, type=Path)
    args = ap.parse_args()
    result = inventory(args.cohort_root, args.reference_case)
    print(json.dumps(result, ensure_ascii=False, indent=2, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
